@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Customer_Manager as cm
participant System as sys

activate cm
cm -> sys: ask to start the grading process

activate sys
sys --> cm: list and ask to select job offer
deactivate

cm -> sys: select job offer

activate sys
sys --> cm: grades all the applications that have interview results for that job offer
deactivate


deactivate cm
@enduml