@startuml

title UC09 SEQUENCE DIAGRAM

autonumber

actor CostumerManager as cm
participant ShowCandidateDetailsUI as ui
participant ShowCandidateDetailsController as c
participant ShowCandidateDetailsRepository as repo

activate cm

cm -> ui: initializes the program
activate ui

ui --> cm : asks for the candidate id or candidate email
deactivate ui

cm -> ui : inputs id of the desired candidate
activate ui

ui -> c : listCandidateData(int candidateId)
deactivate ui
activate c

c -> repo : findByCandidateId(int candidateId)
deactivate c
activate repo

repo -> c: return the candidate details
deactivate repo
activate c

c -> ui: return the candidate details
deactivate c
activate ui

ui -> cm: shows the candidate details
deactivate ui
deactivate cm

@enduml