@startuml

left to right direction


actor Administrator as adm

adm --> (UC01 - Register users of the backoffice)
adm --> (UC02 - Enable users of the backoffice)
adm --> (UC03 - Disable users of the backoffice)
adm --> (UC04 - List users of the backoffice)

actor CustomerManager as cm

cm --> (UC05 - Register customer)
cm --> (UC06 - Register job opening)
cm --> (UC07 - List job openings)
cm --> (UC08 - List applications for a job opening)
cm --> (UC09 - Display data of a candidate)
cm --> (UC10 - Setup phases of the process for a job opening)

actor LanguageEngineer as le

le --> (UC15 - Develop a plugin)

actor Operator as op

op --> (UC11 - Register a candidate)
op --> (UC12 - List candidates)
op --> (UC13 - Register application of a candidate)
op --> (UC14 - Generate template file to help collect data from candidates)

actor ProjectManager as pm

pm --> (UC15 - Support and apply authentication and authorization for all its users and functionalities)

' Sprint C

cm --> (UC16 - Rank the candidates for a job opening)

cm --> (UC17 - Edit a job opening)

op --> (UC18 - Enable candidate)
op --> (UC19 - Disable candidate)

cm --> (UC20 - Execute the process that verifies the requirements of the applications for a job opening)

cm --> (UC21 - Open/Close phases of the process for a job opening)

cm --> (UC22 - Record the time and date for an interview with a candidate)

cm --> (UC23 - Upload a text file with the candidate responses for an interview)

cm --> (UC24 - Execute the process that evaluates grades the interviews for a job opening)

cm --> (UC25 - Get an ordered list of candidates, using the job interview points)

cm --> (UC26 - Publish the results of the selection of candidates for a job opening)

cm --> (UC27 - Display all the data of an application)

op --> (UC28 - Upload a text file with the data fields of a candidate for its verification)

actor Candidate as c

c --> (UC29 - list all my applications and their state)

actor Customer as cus

cus --> (UC30 - List all my job openings)

@enduml
