@startuml

title UC03 SYSTEM SEQUENCE DIAGRAM

autonumber

actor User as u
participant System as s

u -> s: starts the process to disable user

s -> u: shows the list of users and asks to select one

u -> s: selects one user

s -> u: asks for confirmation

u -> s: confirms

@enduml